### ISSUE TITLE
Failed to load Controllers automatically on 1.5.0

### ISSUE THREAD

**Issue by linux-china** [mandarineorg/mandarinets#139]
If controller components are in different TS files, and can not be loaded  automatically.  Inlined controller class in server.ts  file is fine. 

![image](https://user-images.githubusercontent.com/46711/89844263-e4fdb700-db2f-11ea-9bf4-6a23060ca929.png)

**Comment by andreespirela** [comment]
Yes. This is right. I just realized we are missing the `entry-point` documentation from the new docs ([here](https://www.mandarinets.org/docs/master/mandarine/introduction)). 

The logic behind the `entry-point` is to accumulate all the references of your files in a single file which is the file you will run with deno. You can find this documentation in our legacy documentation [here](https://mandarineframework.gitbook.io/mandarine-ts/mandarine-core/core-initialization#single-entry-point-file).

![image](https://user-images.githubusercontent.com/60560109/89844718-68c49d00-db4a-11ea-8cdc-112a6482e3a3.png)

So let's say, in the picture you attached. You will create a `entry-point` file anywhere, in this file you will include all your references

```typescript
import { ........ } from "https://deno.land/x/mandarinets@1.5.0/mod.ts"
import { MyController } from "../MyController.ts" // for example
import { MyService } from "../MyService.ts" // for example

const controllers = [MyController];
const services = [MyService];
 
.....

new MandarineCore().MVC().run();
```
and then you would `deno run` that entry-point file. Let me know if there are further questions

**Comment by andreespirela** [comment]
@buttercubz Do you think this can be improved through the CLI or Mandarine's core itself? It's kind of hacky because Deno will need the imports anyway so I don't see any possible way with javascript & V8 to automatically detect the imports to use, but I think there's a work to be done here. Any thoughts @buttercubz ? Any thought is very well appreciated

**Comment by buttercubz** [comment]
> @buttercubz Do you think this can be improved through the CLI or Mandarine's core itself? It's kind of hacky because Deno will need the imports anyway so I don't see any possible way with javascript & V8 to automatically detect the imports to use, but I think there's a work to be done here. Any thoughts @buttercubz ? Any thought is very well appreciated

We have already created a system to handle the dependencies without the use of the import map, we have that version in case the deno ends the support for the import map, maybe that same system can work in mandarine cli

**Comment by buttercubz** [comment]
@andreespirela 
Can you detail the problem for me to implement a prototype in mandarine cli?

**Comment by andreespirela** [comment]
@buttercubz Thanks, will do!

**Comment by linux-china** [comment]
@andreespirela  Got. I'm a Spring Boot Develper. :)   and  I think Mandarine.TS  will load all TS files from the src/main/mandarine and load the components automatically like Spring Boot App.    Any plan to support this feature?  For a Java developer, and I really like Mandarine.TS.  👍

**Comment by andreespirela** [comment]
@linux-china Great to hear that! Mandarine was mainly inspired on Spring boot but now we are taking a different approach to give it a Mandarine flavour. Yes, we want to support the auto-scan feature to reference all the needed files like you described, we are not sure yet how we will approach it because of the way Javascript  and specially the V8 engine work, but it’s definately on the roadmap.

**Comment by andreespirela** [comment]
Closing as no further comment was added and seems like the user could solve it with the mentioned indications
