### ISSUE TITLE
Other Transport Layers

### ISSUE THREAD

**Issue by damianesteban** [mandarineorg/mandarinets#225]
**[Context]**
I would like to see (and potentially help build) other kinds of transport laters, i.e. SQS, Redis, Nats, etc.

**[Alternatives]**
[NestJS has something similar](https://docs.nestjs.com/microservices/basics).

**[Currently implemented]**
[NestJS has something similar](https://docs.nestjs.com/microservices/basics).

**[Additional context]**

I need to become more familiar with Deno and then I would be happy to help with this.

**Comment by andreespirela** [comment]
This is something we want to do. We want to implement microservices, but I’m not sure how to approach that... it would be nice if you can elaborate on this, just a minimal example on the way you see it...

As far as I understand, a microservice would have a handler (which is pretty much a JS function) so the messages would be sent to that JS function (handler), just like an HTTP server in JS works but instead of HTTP requests, it would be messages from the microservice providers. Is this understanding right?

> I need to become more familiar with Deno and then I would be happy to help with this.
Absolubtely, As many hands as we can are welcome. Mandarine is always looking for new collaborators, and I am sure this is a huge feature to implement where help will be gladly received.

**Comment by andreespirela** [comment]
I want to implement the first part of it by 3.0.0, the idea is to allow websockets to be mandarine-powered. Deno already has a websocket API, I think there's something that can be done here.

**Comment by andreespirela** [comment]
Closing as it is being addressed in #274 . For future references please refer to #274
