### ISSUE TITLE
Support static content

### ISSUE THREAD

**Issue by ThauEx** [mandarineorg/mandarinets#35]
Looks like it's currently not possible to define a folder for static content. Oak seems to support it (https://github.com/oakserver/oak#static-content), what about having a config where this path gets defined and if it is defined, the given folder is used for static files?

**Comment by andreespirela** [comment]
That would mean a static folder where you would save files and you would access to them easily, for example:
- static
    - mycss.css

http://localhost:8080/mycss.css would retrieve /static/mycss.css.

Is this understanding right?

**Comment by ThauEx** [comment]
Yes, you are right. This is quite useful for js and css files, otherwise a separate controller would be required for that.

**Comment by andreespirela** [comment]
Good. This should be available in 1.0.1. Currently being worked on. @ThauEx 1.0.1 should be coming in the next couple of hours.

**Comment by ThauEx** [comment]
Wow, thats sounds really good. Thank you very much.

**Comment by andreespirela** [comment]
Following up on this issue. We are investigating whether we should allow handling resources in the root of the url, "/". or resources should be located under "/static". It is planned to be customizable & implementable, we are currently refactoring the written code in order to decide. @ThauEx Thanks for your patience here.

Regards.

**Comment by andreespirela** [comment]
This is merged. Documentation https://app.gitbook.com/@mandarineframework/s/mandarine-ts/v/v1.0.1/mandarine-mvc/serving-static-content
