### ISSUE TITLE
Template engine from config is ignored

### ISSUE THREAD

**Issue by ThauEx** [mandarineorg/mandarinets#38]
Hey,
thank you for adding denjucks as a template engine, but now to my issues.
When I configure the engine inside the controller, as it has been done in the examples, it's working, but when I use the config file and set something like this:
```json
    "templateEngine": {
      "path": "./templates",
      "engine": "denjucks"
    }
```
it won't pick up the configured engine, it's using ejs all the time. So doesn't matter which (valid) engine gets configured, ejs is used all the time.

And (not sure if it is and issue on view_engine), but when using denjucks and then extend tag (` {% extend 'some_template.html' %}`), it's not using the configured template path, but the project root. So when using the configured path from above, I have to use `{% extend 'templates/some_template.html'%}`. I could do some more research if you want and open another issue for that.

**Comment by andreespirela** [comment]
Hello.
In regards to point 1, I will be running some tests and see what is going on. It sounds like a bug.

In regards to point two, that is something of Denjucks. Maybe there can be some workaround if it has the option to configure the template folder where it reads the inclusion. We will check this out but directly, it is not related to Mandarine. Let’s see if there’s some workaround to it

**Comment by andreespirela** [comment]
@ThauEx I can't seem to reproduce this behavior. are you sure the property `templateEngine` is inside the property `mandarine`?. It should look like this:
```typescript
    "mandarine": {
        "templateEngine": {
            "engine": "denjucks"
        }
    }
```

**Comment by ThauEx** [comment]
I cleared the cache, but the issue persists. My config looks like this:
```json
{
  "mandarine": {
    "server": {
      "port": 9999
    },
    "resources": {
      "staticFolder": "./public"
    },
    "templateEngine": {
      "path": "./templates",
      "engine": "denjucks"
    }
  }
}
```

When I enter something invalid as engine, it throws an error. So the config should be correct.
I can try to prepare an example if you want.

**Comment by andreespirela** [comment]
Sure. Let me see your code, the command you’re running to start up the application, and an screenshot with your folder’s structure (so directories and files). From that I will try to run it and see what’s going on.

**Comment by ThauEx** [comment]
Okay, great. I will provide it tomorrow (it already late here).

**Comment by andreespirela** [comment]
Great. Make sure you’ve ran —reload, and your whole app is pointing to @v1.0.1 . Sorry for this inconvenience, when the details are provided I will investigate further.
Regards.

**Comment by andreespirela** [comment]
@ThauEx Please also provide the code of the template. Regards.

**Comment by ThauEx** [comment]
Here is a sample project, run it via `deno run --config tsconfig.json --allow-net --allow-read --unstable app.ts`
It has two endpoints:
http://localhost:9999/test
http://localhost:9999/test2
Both should show the same, but the second one has the template engine configured inside the controller and the first one is taking it from the config (whrer the same is configured)
[project.zip](https://github.com/mandarineorg/mandarinets/files/4744236/project.zip)

If you need more, just tell me and thank you for the inventigation.

**Comment by andreespirela** [comment]
@ThauEx I see why this is happening. I am glad to inform it is not a bug :).
![Screen Shot 2020-06-08 at 12 46 44 PM](https://user-images.githubusercontent.com/60560109/84057783-2c2bc800-a986-11ea-8442-a0b723b1652a.png)
Here is a proof that it's working.
What was happening was, Mandarine.MandarineCore.setConfiguration is deprecated, it should not be used at all since if it's used, then the configuration will load after Mandarine's engine has loaded which when it gets to that point, it will be pointless to load the view engine from the configuration as it has been loaded already with its default value.
Instead, your configuration file **must** be name _properties.json_ and it should be located in ./src/main/resources (**./src/main/resources/properties.json**) [Please read this section of the documentation to see more](https://mandarineframework.gitbook.io/mandarine-ts/mandarine-core/properties#setting-your-own-properties)
I am attaching your folder with the **properties.json** inside the directory it's supposed to be, and also for you to test it out, it should be working properly now.
[project.zip](https://github.com/mandarineorg/mandarinets/files/4747381/project.zip)

In regards to your second request:
```
And (not sure if it is and issue on view_engine), but when using denjucks and then extend tag ( {% extend 'some_template.html' %}), it's not using the configured template path, but the project root. So when using the configured path from above, I have to use {% extend 'templates/some_template.html'%}. I could do some more research if you want and open another issue for that.
```   
I am afraid we are unable to do this at the time as it would mean to change everything in the engine just to add that feature. We could work this out if our [view engine provider](https://github.com/deligenius/view-engine) makes the required "infrastructure" for it, I highly encourage you to open a ticket for this in the _view engine repository_ and if they make the changes to support this possible feature, then we could adapt it.

Coming back to the original issue: Please read the documentation I have attached, perhaps test the code that I have attached as well, and let me know if this issue was solved so I can close this issue. 

Regards.

**Comment by ThauEx** [comment]
Thank you very much. I have not noticed the deprecation of `Mandarine.MandarineCore.setConfiguration`. 
For the scond thing, I will have a look on `view-engine` and will maybe open an issue there.
