### ISSUE TITLE
error: Failed to get compiled source code of https://deno.land/x/denjucks/src/deps/path/std/path/mod.ts.

### ISSUE THREAD

**Issue by WhoAdarshPandya** [mandarineorg/mandarinets#58]
got error by running this command : 
`deno run --config tsconfig.json --allow-net --allow-read myFile.ts`

`error: Failed to get compiled source code of https://deno.land/x/denjucks/src/deps/path/std/path/mod.ts.
Reason: The system cannot find the path specified. (os error 3)`

File tree: 
> myFile.ts
> tsconfig.json

it was working fine 2 or 3 days ago

**Comment by andreespirela** [comment]
I will look into this. Can you please share your myFile.ts, and a picture of your File tree just to verify and reproduce. Thanks

**Comment by andreespirela** [comment]
@WhoAdarshPandya I would like to mention there were some fundamental changes in v1.1.1 which included the modification of some source URLS. I just ran the [quick example](https://mandarineframework.gitbook.io/mandarine-ts/getting-started/quick-example) and it worked fine. But I do want to mention I ran it with the flag **--reload**. **--reload** will empty the cache folder and re-download all the modules. Instead of doing `deno run --config tsconfig.json --allow-net --allow-read myFile.ts`, please **do:** `deno run --config tsconfig.json --allow-net --allow-read --reload myFile.ts`

If `--reload` didn't do it, try pointing out to an earlier version of Mandarine such as v1.1.0 you can do this by `import { ...... imports .... } from "https://deno.land/x/mandarinets@v1.1.0/mod.ts"; Remember to replace ** ...... imports ....** with the modules of Mandarine you are using.

I will be waiting for your feedback on this as well as your code and an screenshot of your file tree just to verify and try to reproduce the behavior as much as possible.

Best.

**Comment by WhoAdarshPandya** [comment]
hey man, Thanks for the solution
it's now working fine i just have to specify version of mandarinets as `mandarineTS@v1.1.0/mod.ts` and while i run i have to specify 
`--reload `flag
![Screenshot (571)](https://user-images.githubusercontent.com/31694369/85876087-d2832480-b7f2-11ea-98c2-b90584d9fb79.png)

**Comment by andreespirela** [comment]
@WhoAdarshPandya Great. Although, try to specify the latest version @v1.1.1 and run `--reload` with it, it should not be broken in version 1.1.1. Let me know if it works with @v1.1.1, if it does then I'm glad the issue is solved, otherwise we will have to mark this as a bug and investigate further

**Comment by WhoAdarshPandya** [comment]
@andreespirela , it is not working when i specify the version as `mandarinets@v1.1.1` , but it is working fine in version `1.1.0`
although it is same error as it was earlier...

**Error** : 
`error: Failed to get compiled source code of https://deno.land/x/denjucks/src/deps/path/std/path/mod.ts.
Reason: The system cannot find the path specified. (os error 3)`

works fine in : **v1.1.0**
breaks in : **v1.1.1**

**Comment by andreespirela** [comment]
Good to know. You are running the quick example found on the docs or you are writing some specific code? @WhoAdarshPandya. If you are writing some specific code, if there is not problem, I would like you to attach the code you are using, if you don't want to attach the code that's ok, we will investigate further anyway. 

Thanks for reporting this

**Comment by andreespirela** [comment]
**[Details]**
Deno is not capable of finding the module `https://deno.land/x/denjucks/src/deps/path/std/path/mod.ts` on version 1.1.1.

**[Environment]**
This bug is taking place in **v1.1.1**

**[Investigation]**
Awaiting for investigation. A possible theory to this problem suggest that the cache folder is not being completely emptied with `--reload` thus it is having a conflict.

**[Status]**
Being investigated and pointing out to be solved for 1.1.2

**Comment by WhoAdarshPandya** [comment]
> Good to know. You are running the quick example found on the docs or you are writing some specific code? @WhoAdarshPandya. If you are writing some specific code, if there is not problem, I would like you to attach the code you are using, if you don't want to attach the code that's ok, we will investigate further anyway.
> 
> Thanks for reporting this

@andreespirela i'm trying this framework , i'm just going through docs and doing things , so sorry there is no specific code or project , will share if i make one :)

**Comment by andreespirela** [comment]
> > Good to know. You are running the quick example found on the docs or you are writing some specific code? @WhoAdarshPandya. If you are writing some specific code, if there is not problem, I would like you to attach the code you are using, if you don't want to attach the code that's ok, we will investigate further anyway.
> > Thanks for reporting this
> 
> @andreespirela i'm trying this framework , i'm just going through docs and doing things , so sorry there is no specific code or project , will share if i make one :)

Got it. Great no worries. I'll work on this and you'll be let know when this is solved. It should be rolling out next week.

**Comment by andreespirela** [comment]
@WhoAdarshPandya Following up on this issue. Can you run `deno --version` and tell me what version of Deno you have, thanks.

**Comment by WhoAdarshPandya** [comment]
> @WhoAdarshPandya Following up on this issue. Can you run `deno --version` and tell me what version of Deno you have, thanks.

Deno v.1.1.2

**Comment by andreespirela** [comment]
We have identified this as a bug and it is being worked on. `In discussion` label has been removed since it is now confirmed as a bug.

**Comment by andreespirela** [comment]
We have identified this as an external issue. [See here](https://github.com/denjucks/denjucks/issues/9).
Cc: @gjuoun
It seems like it is only happening in Windows

**Comment by andreespirela** [comment]
@WhoAdarshPandya This should have been solved in [v1.1.2](https://github.com/mandarineorg/mandarinets/releases/tag/v1.1.2). **Note** that you will not be able to use Denjucks.

Try pointing out to @v1.1.2 and let me know if your mandarine starts working fine again. **Remember** to use the flag `--reload`

**Comment by WhoAdarshPandya** [comment]
yup , it is working fine when i point to `v1.1.2`. `https://deno.land/x/mandarinets@v1.1.2/mod.ts` is working absolutely fine :)
Thank you 👍

**Comment by andreespirela** [comment]
This has been confirmed as working and will be closed.
